site_name: Red Hat Enterprise Linux イメージモード デモ
repo_url: https://github.com/tnk4on/redhat-image-mode-demo/
edit_uri: blob/main/
site_author: Alessandro Rossi - Red Hat (日本語翻訳版)
site_description: GitHub でホストされている Red Hat Enterprise Linux (RHEL) イメージモード デモのドキュメントページです。
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Red Hat Display
  features:
    - content.code.copy
    - navigation.expand
    - content.tooltips
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え
extra_css:
  - stylesheets/extra.css
nav:
  - ホーム: index.md
  - はじめに:
    - RHEL イメージモードの紹介: getting-started/introduction.md
    - クイックスタート: getting-started/quickstart.md
    - プロジェクトへの貢献:
        - 貢献ガイドライン: getting-started/contributing.md
        - 変更のレビューとテスト: getting-started/review-and-test-changes.md
  - ユースケース:
    - シンプルな RHEL コンテナの構築: use-cases/bootc-container-simple/README.md
    - Apache RHEL イメージの構築: use-cases/bootc-container-httpd/README.md
    - RHEL bootc コンテナを使用して Anaconda と Kickstart で RHEL 9 VM を起動: use-cases/bootc-container-anaconda-ks/README.md
    - パッケージと設定を追加して RHEL bootc コンテナベースの VM を更新: use-cases/bootc-container-update/README.md
    - RHEL 9 bootc コンテナベースの VM を RHEL 10 にアップグレード: use-cases/bootc-container-upgrade/README.md
    - 既存の VM に別の RHEL コンテナイメージを適用: use-cases/bootc-container-replace/README.md
    - bootc-image-builder を使用して VM 用 RHEL QCOW イメージを生成: use-cases/bootc-image-builder-qcow/README.md
    - bootc-image-builder を使用して VM 用 RHEL ISO イメージを生成: use-cases/bootc-image-builder-iso/README.md
    - bootc-image-builder を使用して AWS インスタンス用 RHEL AMI イメージを生成: use-cases/bootc-image-builder-ami/README.md
    - Red Hat Insights で RHEL イメージモードシステムを管理: use-cases/image-mode-management-insights/README.md
    - RHEL イメージモードの活用方法:
      - はじめに: use-cases/image-mode-way-of-working/README.md
      - デモの設定: use-cases/image-mode-way-of-working/demo-build.md
      - 第1章 - ゴールデンイメージの操作: use-cases/image-mode-way-of-working/chapter1.md
      - 第2章 - アップデートとアップグレードの操作: use-cases/image-mode-way-of-working/chapter2.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative $config_dir
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - attr_list
  - pymdownx.emoji
  - abbr
plugins:
  - macros
  - mermaid2
  - search
